### ISSUE TITLE
Investigate category and cluster

### ISSUE THREAD

**Issue by skodapetr** [siret/similant#11]
A cluster has only one individual, but despite that, they do not share the same list of descriptors.

![image](https://user-images.githubusercontent.com/3341693/54346652-bd0dd980-4645-11e9-8664-ca4bec8fefc5.png)

**Comment by skodapetr** [comment]
Another example:

![image](https://user-images.githubusercontent.com/3341693/54347396-3fe36400-4647-11e9-93ab-e227579a200c.png)

**Comment by dragoniscz** [comment]
Duplicate of #12, should by fixed, testing required.
