### ISSUE TITLE
When clicking from one individual to another, labels keep piling up

### ISSUE THREAD

**Issue by jakubklimek** [siret/similant#12]
When I select an individual an then another one, then the first one and then the other one, etc. the labels in the word cloud are always only added, not removed.
I start with:
![image](https://user-images.githubusercontent.com/718827/54347310-0d396b80-4647-11e9-976a-e9693ebd619f.png)
And after a while end up with:
![image](https://user-images.githubusercontent.com/718827/54347329-1a565a80-4647-11e9-82f3-2327fafe4504.png)

**Comment by dragoniscz** [comment]
Should be fixed in #9, testing may be required.
